# Generated by Django 2.2 on 2020-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20200918_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
    ]
